name: root@apolinario VPS 24/7

on:
  schedule:
    - cron: '0 */5 * * *'  # Every 5 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # Just under 5 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to apolinario
        run: sudo hostnamectl set-hostname apolinario

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Create user apolinario with sudo
        run: |
          if ! id -u apolinario >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash apolinario
            echo "apolinario:apolinario" | sudo chpasswd
            sudo usermod -aG sudo apolinario
            echo "apolinario ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/apolinario
          fi

      - name: Clone private repo with token
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nicplayerr/deplay-bot.git /opt/deplay-bot

      - name: Build Docker images
        run: |
          cd /opt/deplay-bot
          docker build -t debian-vps -f Dockerfile.debian .
          docker build -t ubuntu-vps -f Dockerfile.ubuntu .

      - name: Install Python deps and start bot
        run: |
          cd /opt/deplay-bot
          pip install --upgrade pip
          pip install discord.py docker psutil
          nohup python3 bot.py &>/dev/null &

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Show Tmate INFO
        run: |
          echo "🔑 tmate SSH session:"
          cat $HOME/.tmate.sock/ssh

      - name: Sleep to keep VPS alive
        run: sleep 18000  # 5 hours
